In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [328]:
import numpy as np

!pip install numpy  <<<< ใช้สำหรับลงสิ่งที่ไม่มีในเครื่อง
np.__version__ <<<< เอาไว้ดูเวอร์ชั่น

เลขเวอร์ชั่นสำคัญมาก เพราะเรามักเอาโค้ดคนอื่นมาใช้ในงานของเราซึ่งมันอาจทำให้ติดปัญหาเพราะเวอร์ชั่นไม่ตรงกัน

In [1]:
!pip install numpy

In [4]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

1D Array / Vector

In [6]:
a = np.array([[1,2,3] ,
             [4,5,6] , 
             [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2D Array / Matrix

In [7]:
a[0]

array([1, 2, 3])

**การ access array พวกนี้ออกสอบ**

In [9]:
a = np.array([1,2,3,4,5,6,7])
a[2:5]

array([3, 4, 5])

array ที่ 2 ถึง 5

In [10]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [11]:
a[3:]

array([4, 5, 6, 7])

In [34]:
L = [1,2,3,4,5,6,7,8,9]
L

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
L[:6]

(1, 2, 3, 4, 5, 6)

In [17]:
a[-1]

7

ตำแหน่งสุดท้าย 

In [18]:
a[-2]

6

ถอยจากหลังสุดมาสอง

In [19]:
a[2:-3]

array([3, 4])

In [20]:
a[-5:]

array([3, 4, 5, 6, 7])

In [21]:
a[-5:-1]

array([3, 4, 5, 6])

ตำแหน่งที่ถอยมา 5 ถึงตำแหน่งที่ถอยมา 1

In [22]:
a[-2:2]

array([], dtype=int64)

อันนี้ช่วงมันกลับด้าน ทำให้ไม่มีเลข

In [23]:
np.size(a)

7

ขนาดของ array

In [24]:
np.shape(a)

(7,)

แสดงขนาดแบบเวคเตอร์

In [27]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
a[a[2]]

4

a[2] = 3

a[3] = 4

ทำด้านในออกด้านนอก

In [35]:
L

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
L[L[3]]

5

L[3] = 4

L[4] = 5

In [37]:
L.reverse()
L

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [42]:
np.sort(a)[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [43]:
sorted(a, reverse = True)


[7, 6, 5, 4, 3, 2, 1]

In [44]:
a = a.reshape(1,7)
np.shape(a)

(1, 7)

พวกนี้ใช้บ่อยในการตัดเวคเตอร์ออกจากเมทริกซ์ละยัดเข้าไปใหม่

In [45]:
a

array([[1, 2, 3, 4, 5, 6, 7]])

Matrix

In [46]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

Vector

In [47]:
a = np.array([[1,2,3] ,
             [4,5,6] , 
             [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
L = [[1,2,3] ,[4,5,6] , [7,8,9]]
L

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [49]:
a[0,0]

1

List ไม่สามารถ access แบบ matrix ได้

In [50]:
L[0][0]

1

In [51]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
a[1,:]

array([4, 5, 6])

แนะนำให้ใส่ด้านหลังด้วย จะได้รู้ว่าเอามาทั้งแถว

In [53]:
L[1][:]

[4, 5, 6]

In [54]:
a[1]

array([4, 5, 6])

In [55]:
a[: , -1]

array([3, 6, 9])

เอาคอลลัมน์สุดท้ายมา

In [56]:
a[: , 0]

array([1, 4, 7])

In [57]:
L[:][0]

[1, 2, 3]

คำตอบไม่ตรงเพราะมันไม่ได้ recognize เป็น matrix
เพราะฉะนั้นในการเอาข้อมูลมา ควรทำให้เป็น array เพื่อให้ access ข้อมูลด้วยหลัก และ แถว อย่างแม่นยำ

In [58]:
a[:,1] = 0
a

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])

การ set comlumn 1 to be 0

In [59]:
a[1,:] = 0
a

array([[1, 0, 3],
       [0, 0, 0],
       [7, 0, 9]])

การ set row 1 to be 0

In [68]:
a[0:2 , :] = 1
a

array([[1, 1, 1],
       [1, 1, 1],
       [7, 0, 9]])

0 ถึง 2 
มันจะเป็น [0,2)
เอา 0 1 แต่ไม่เอา 2

In [64]:
a.shape

(3, 3)

In [65]:
np.size(a,0)

3

0 นับแถว
1 นับคอลัมน์

In [66]:
np.size(a)

9

In [67]:
np.ndim(a)

2

มีกี่ไดเมนชั่น
ใช้ a.ndim ก็ได้

In [69]:
x = np.array([1,2,3,4,5,6,7])
x

array([1, 2, 3, 4, 5, 6, 7])

In [72]:
x[::3]

array([1, 4, 7])

In [73]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix


array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [74]:
np.array(np_mix_matrix[:,1], dtype = int)

array([2, 4, 6])

identify it as int

In [75]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [76]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [77]:
c = np.full((2,2),8)
c

array([[8, 8],
       [8, 8]])

In [78]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

matrix เอกลักษณ์

In [79]:
c*d

array([[8., 0.],
       [0., 8.]])

แบบนี้มันคูณตำแหน่งเดียวกันเฉยๆ แต่มันไม่คูณ matrix

In [81]:
np.matmul(c,d)

array([[8., 8.],
       [8., 8.]])

In [82]:
2*np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

In [83]:
np.ones((2,2))*2

array([[2., 2.],
       [2., 2.]])

In [85]:
np.sqrt(np.full((2,2),9))

array([[3., 3.],
       [3., 3.]])

square root matrix

In [87]:
np.empty([4,4])

array([[4.68563231e-310, 0.00000000e+000, 2.41907520e-312,
        2.37663529e-312],
       [2.22809558e-312, 2.46151512e-312, 6.79038654e-313,
        2.35541533e-312],
       [2.46151512e-312, 6.79038654e-313, 2.35541533e-312,
        6.79038654e-313],
       [2.14321575e-312, 2.22809558e-312, 2.14321575e-312,
        2.14321575e-312]])

จองอาเรย์เปล่า

In [91]:
b = np.ones((2,2))*2 **3
b

array([[8., 8.],
       [8., 8.]])

In [92]:
np.random.rand()

0.8798298069114444

เลขที่สุ่มออกมาจะอยู่ในช่วง 0 ถึง 1

In [93]:
np.random.rand()*10

6.057707059061768

สุ่มตั้งแต่เลข 0 ถึง 10

In [94]:
np.round(np.random.rand()*10)

8.0

ปัดเศษ

In [95]:
[np.round(np.random.rand()*10) for item in range(10)]

[5.0, 5.0, 0.0, 7.0, 4.0, 9.0, 6.0, 1.0, 7.0, 7.0]

random เลข 0-9 มา 10 ครั้ง

In [109]:
np.random.randint(5)

3

random 0-4

In [110]:
[np.random.randint(5) for item in range(10)]

[0, 2, 3, 1, 4, 3, 0, 3, 2, 1]

In [115]:
np.random.rand(3,3)

array([[0.53316528, 0.69187711, 0.31551563],
       [0.68650093, 0.83462567, 0.01828828],
       [0.75014431, 0.98886109, 0.74816565]])

In [120]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([9, 2, 7, 8, 8])

สุ่มหยิบ 5 เลขจากทั้งหมด แต่เลขซ้ำได้

In [122]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5 , replace = False)

array([3, 4, 5, 7, 1])

สุ่มหยิบ 5 เลขจากทั้งหมด โดยที่เลขไม่ซ้ำ

In [138]:
np_matrix = np.round(np.random.rand(5,5)*100)
np_matrix

array([[62., 47., 47., 72., 29.],
       [38., 75., 88., 10.,  9.],
       [35., 55.,  3., 97., 32.],
       [22., 14., 10., 98., 26.],
       [54., 45., 10., 35., 47.]])

generate 3 row, 5 column

In [139]:
idx_choose = np.random.choice(5,3, replace = False)
idx_choose

array([1, 2, 0])

จาก 5 แถว เลือกมา 3 ตัว โดยที่ไม่ซ้ำกัน

In [140]:
np_matrix_choose = np_matrix[idx_choose, :]
np_matrix_choose

array([[38., 75., 88., 10.,  9.],
       [35., 55.,  3., 97., 32.],
       [62., 47., 47., 72., 29.]])

เอาข้อมูลที่เลือกมาแสดง

In [144]:
np_matrix = np.random.randint(3,size =(5,5))
np_matrix

array([[1, 1, 2, 0, 1],
       [1, 1, 1, 1, 2],
       [2, 2, 0, 1, 2],
       [1, 1, 1, 1, 0],
       [2, 2, 0, 1, 1]])

In [146]:
i, j = np.where(np_matrix == 2)
[(i[ii], j[ii]) for ii in range(len(i))]

[(0, 2), (1, 4), (2, 0), (2, 1), (2, 4), (4, 0), (4, 1)]

บอกตำแหน่งที่มีเลข 2

In [147]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

array([[1, 1, 2, 0, 1],
       [1, 1, 1, 1, 0],
       [2, 2, 0, 1, 1]])

In [158]:
np_matrix = np.random.randint(3,size =(5,5))
np_matrix

array([[1, 1, 2, 1, 1],
       [0, 1, 2, 1, 1],
       [0, 0, 1, 1, 2],
       [1, 2, 2, 1, 2],
       [2, 0, 1, 1, 1]])

In [159]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

array([[1, 1, 2, 1, 1],
       [1, 2, 2, 1, 2],
       [2, 0, 1, 1, 1]])

0 คือแถว 1 คือคอลัมน์
เอาแถวที่ 1 2 ออก 

In [160]:
np_matrix = np.delete(np_matrix,[1,2],1)
np_matrix

array([[1, 1, 1],
       [1, 1, 2],
       [2, 1, 1]])

เอาคอลัมน์ที่ 1 2 ออก

In [152]:
rng = np.random.RandomState(0)
np_matrix = rng.randint(3, size = (5,5))
np_matrix

array([[0, 1, 0, 1, 1],
       [2, 0, 2, 0, 0],
       [0, 2, 1, 2, 2],
       [0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1]])

ประกาศ seed ทุกครั้งที่ใช้

In [155]:
rng = np.random.RandomState(0)
rng.rand()

0.5488135039273248

แบบใหม่ สั่งแบบนี้จะได้ค่าเดิมตลอด seed ไม่เวิคแล้ว

In [156]:
rng = np.random.RandomState(0)
[np.round(rng.rand()*10) for item in range(10)]

[5.0, 7.0, 6.0, 5.0, 4.0, 6.0, 4.0, 9.0, 10.0, 4.0]

In [157]:
rng = np.random.RandomState(0)
rng.randint(5)

4

In [161]:
np_matrix

array([[1, 1, 1],
       [1, 1, 2],
       [2, 1, 1]])

In [162]:
a = np_matrix == 2
a

array([[False, False, False],
       [False, False,  True],
       [ True, False, False]])

ตำแหน่งไหนเป็นเลข 2 จะมาร์คเป็น True ให้

In [163]:
np_matrix[a] = 99
np_matrix

array([[ 1,  1,  1],
       [ 1,  1, 99],
       [99,  1,  1]])

เปลี่ยนทุกจุดที่เป็น 2 ให้เป็น 99

In [164]:
np_matrix[np_matrix == 99] = 33
np_matrix

array([[ 1,  1,  1],
       [ 1,  1, 33],
       [33,  1,  1]])

ทำแบบด้านบนแต่สั้นลง