In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import numpy as np

# #Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.

In [2]:
rng = np.random.RandomState(0)
np_matrix = rng.rand(10,5)
np_matrix[:,4] = np.round(np_matrix[:,4])
np_matrix

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.        ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.        ],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.        ],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 1.        ],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.        ],
       [0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.        ],
       [0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.        ],
       [0.6176355 , 0.61209572, 0.616934  , 0.94374808, 1.        ],
       [0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 1.        ],
       [0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.        ]])

# #Ex 3. Why we cannot use this index ? Please fix it !!
---------------------------------------------------------------
idx = [1,2,3,4,5]
np_matrix[idx,:]

---------------------------------------------------------------------------
IndexError Traceback (most recent call last)
<ipython-input-67-9b0cced7972b> in <module>
      1 idx = [1,2,3,4,5]
----> 2 np_matrix[idx,:]

IndexError: index 5 is out of bounds for axis 0 with size 5
    
**Ans**
    index : = 5 indexes แต่เรามี 4 indexes ดังนั้นเราสามารถลดจำนวน : ลง 1 เพื่อให้มันไม่ error
    
    >>>>> จากการใช้ตัวแปรที่ซ้ำกัน ทำให้โค้ดเอ๋อ เลยเปลี่ยน : เป็นเลข 5 ตามจำนวน index ที่นับได้แทนนะคะ
*  [idx, :-1]
*  [idx, 4]    

In [10]:
idx = [1,2,3,4,5]
np_matrix[idx,5-1]

array([0., 0., 1., 0., 0.])

In [11]:
idx = [1,2,3,4,5]
np_matrix[idx,4]

array([0., 0., 1., 0., 0.])

# Ex 4. Randomly create a data matrix of 10 samples with 5 features. 
---------------------------------------------------------------------
* Then, randomly create a label vector for 10 samples. 
* Finally, seperate samples into 2 groups
* Group 1 called train_data (label == 0)
* Group 2 called test_data (label == 1)


In [13]:
rng = np.random.RandomState(0)
main_matrix = rng.randint(10, size = (10,5))
main_matrix

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7],
       [3, 2, 7, 2, 0]])

In [20]:
rng = np.random.RandomState(0)
data_matrix = rng.randint(2 ,size = 10)
data_matrix

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [22]:
train_data = main_matrix[np.where(data_matrix == 1)]
train_data

array([[9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7],
       [3, 2, 7, 2, 0]])

In [ ]:
test_data = main_matrix[np.where(data_matrix == 0)]